---
name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Set up JDK 11"
        uses: "actions/setup-java@v1"
        with:
          java-version: "11.0.3"

      - name: "Build"
        run: |
          ant -f tlatools/org.lamport.tlatools/customBuild.xml info clean compile compile-test dist

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            tlatools/org.lamport.tlatools/dist/*.jar
